# Generated by Django 4.2.30 on 2026-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("sq", "Shqip"),
                    ("en", "Anglisht"),
                    ("mk", "Maqedonisht"),
                    ("other", "Gjuhë tjera"),
                ],
                default="sq",
                max_length=10,
                verbose_name="Gjuha",
            ),
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="copy_number",
            field=models.CharField(
                max_length=14, unique=True, verbose_name="Nr. Kopjes (Barkod)"
            ),
        ),
    ]
