# Generated by Django 4.2.30 on 2026-05-28 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("libra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=150)),
            ],
            options={"ordering": ["last_name", "first_name"],},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titulli")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nëntitulli"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="ISBN"),
                ),
                (
                    "year",
                    models.CharField(blank=True, max_length=30, verbose_name="Viti"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Formati (cm)"
                    ),
                ),
                (
                    "pages",
                    models.CharField(blank=True, max_length=50, verbose_name="Faqet"),
                ),
                (
                    "class_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nr. Klasifikimit"
                    ),
                ),
                (
                    "general_note",
                    models.TextField(
                        blank=True, verbose_name="Shënime të përgjithshme"
                    ),
                ),
                (
                    "contents_note",
                    models.TextField(
                        blank=True, verbose_name="Shënime mbi përmbajtjen"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Përmbledhje")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Sasia"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Autor Kryesor"),
                            ("coauthor", "Koautor"),
                            ("editor", "Editor / Redaktor"),
                            ("translator", "Përkthyes"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="libra.author"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_authors",
                        to="libra.book",
                    ),
                ),
            ],
            options={"ordering": ["order", "role"],},
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "loan_date",
                    models.DateField(auto_now_add=True, verbose_name="Data e Huazimit"),
                ),
                ("due_date", models.DateField(verbose_name="Data e Kthimit")),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="Kthyer më"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("returned", "Kthyer"),
                            ("overdue", "Vonuar"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statusi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libra.book",
                        verbose_name="Libri",
                    ),
                ),
            ],
            options={"ordering": ["-loan_date"],},
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Emri")),
                ("last_name", models.CharField(max_length=150, verbose_name="Mbiemri")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefoni"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresa")),
                (
                    "membership_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nr. Anëtarësisë"
                    ),
                ),
                (
                    "membership_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data e Anëtarësimit"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notes", models.TextField(blank=True, verbose_name="Shënime")),
            ],
            options={"ordering": ["last_name", "first_name"],},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.DeleteModel(name="Project",),
        migrations.AddField(
            model_name="loan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="libra.member",
                verbose_name="Anëtari",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libra.publisher",
                verbose_name="Botuesi",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, to="libra.subject", verbose_name="Kategorite"
            ),
        ),
    ]
