# Generated by Django 4.2.30 on 2026-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libra", "0002_book_language_alter_bookcopy_copy_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="shelf_label",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Label Rafti (p.sh. 3-00001)"
            ),
        ),
    ]
